### ISSUE TITLE
To-do list for v4.0.0 final

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#234]
- [x] Add more relevant images to [docs site home page](https://react-querybuilder.js.org/) feature list
- [x] Finalize the [Getting Started](https://react-querybuilder.js.org/docs/intro) page on the docs site
- [x] Update demo links to point to docs site, not README.md
- [x] [Update README.md](https://github.com/react-querybuilder/react-querybuilder/edit/master/README.md) to remove detailed documentation and link to the new docs site instead
- [x] Update link on [repo home page](https://github.com/react-querybuilder/react-querybuilder) to point to the [new docs site](https://react-querybuilder.js.org/)
- [x] Disable [wiki](https://github.com/react-querybuilder/react-querybuilder/wiki)
  - [x] Store "Coming soon" bullets somewhere first. (Done - react-querybuilder/react-querybuilder.github.io#2)
- [x] Create a public IE11 test page for [BrowserStack](https://www.browserstack.com/)
- [x] #232
- [x] Merge `vite` branch
- [x] Cloning a rule/group should insert the clone immediately after the original, not at the end of the group
- [x] #251
- [x] #259
- [x] Code splitting/dynamic imports for custom component packages in demo
- [x] Create icon; add to GitHub organization and docs site

- [x] `lerna publish 4.0.0`
